//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 5732 with alias "profileMember"
	/// <summary>ProfileMember</summary>
	public partial interface IProfileMember : IPublishedContent
	{
		/// <summary>Hide in navigation</summary>
		bool UmbracoNaviHide { get; }
	}

	/// <summary>ProfileMember</summary>
	[PublishedContentModel("profileMember")]
	public partial class ProfileMember : PublishedContentModel, IProfileMember
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "profileMember";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProfileMember(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProfileMember, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hide in navigation
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return GetUmbracoNaviHide(this); }
		}

		/// <summary>Static getter for Hide in navigation</summary>
		public static bool GetUmbracoNaviHide(IProfileMember that) { return that.GetPropertyValue<bool>("umbracoNaviHide"); }
	}
}
