//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>slide2</summary>
	[PublishedContentModel("slide2")]
	public partial class Slide2 : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "slide2";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Slide2(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Slide2, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// contPicker
		///</summary>
		[ImplementPropertyType("contPicker")]
		public IPublishedContent ContPicker
		{
			get { return this.GetPropertyValue<IPublishedContent>("contPicker"); }
		}

		///<summary>
		/// multiPicker
		///</summary>
		[ImplementPropertyType("multiPicker")]
		public IEnumerable<IPublishedContent> MultiPicker
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("multiPicker"); }
		}

		///<summary>
		/// relLinks
		///</summary>
		[ImplementPropertyType("relLinks")]
		public Umbraco.Web.Models.RelatedLinks RelLinks
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("relLinks"); }
		}

		///<summary>
		/// slide
		///</summary>
		[ImplementPropertyType("slide")]
		public IEnumerable<IPublishedContent> Slide
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("slide"); }
		}

		///<summary>
		/// slideTest
		///</summary>
		[ImplementPropertyType("slideTest")]
		public decimal SlideTest
		{
			get { return this.GetPropertyValue<decimal>("slideTest"); }
		}

		///<summary>
		/// testMember
		///</summary>
		[ImplementPropertyType("testMember")]
		public IPublishedContent TestMember
		{
			get { return this.GetPropertyValue<IPublishedContent>("testMember"); }
		}
	}
}
