//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Upload</summary>
	[PublishedContentModel("upload")]
	public partial class Upload : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "upload";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Upload(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Upload, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// body
		///</summary>
		[ImplementPropertyType("body")]
		public IHtmlString Body
		{
			get { return this.GetPropertyValue<IHtmlString>("body"); }
		}

		///<summary>
		/// Insert Form
		///</summary>
		[ImplementPropertyType("insertForm")]
		public IHtmlString InsertForm
		{
			get { return this.GetPropertyValue<IHtmlString>("insertForm"); }
		}

		///<summary>
		/// title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}

		///<summary>
		/// upload2
		///</summary>
		[ImplementPropertyType("upload2")]
		public string Upload2
		{
			get { return this.GetPropertyValue<string>("upload2"); }
		}

		///<summary>
		/// uploader
		///</summary>
		[ImplementPropertyType("uploader")]
		public string Uploader
		{
			get { return this.GetPropertyValue<string>("uploader"); }
		}

		///<summary>
		/// uploading
		///</summary>
		[ImplementPropertyType("uploading")]
		public IEnumerable<IPublishedContent> Uploading
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("uploading"); }
		}
	}
}
